package com.vnshop.sellerfinanceservice.infrastructure.web.pagination;

import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import com.fasterxml.jackson.databind.node.ObjectNode; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Clock; import java.time.Duration; import java.time.Instant; import java.util.Base64; import java.util.Objects; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
public final class AdminCursorCodec { private static final String ALGORITHM="HmacSHA256"; private static final int VERSION=1; private final byte[] secret; private final Duration ttl; private final Clock clock; private final ObjectMapper mapper=new ObjectMapper();
 public AdminCursorCodec(String secret,Duration ttl,Clock clock){if(secret==null||secret.isBlank())throw new IllegalArgumentException("cursor secret is required");if(ttl==null||ttl.isNegative()||ttl.isZero())throw new IllegalArgumentException("cursor ttl must be positive");this.secret=secret.getBytes(StandardCharsets.UTF_8);this.ttl=ttl;this.clock=Objects.requireNonNull(clock,"clock is required");}
 public String encode(Cursor c){Objects.requireNonNull(c,"cursor is required");ObjectNode n=mapper.createObjectNode();n.put("v",VERSION);n.put("resource",required(c.resource(),"resource"));n.put("filterHash",required(c.filterHash(),"filterHash"));n.put("sort",required(c.sort(),"sort"));n.put("sortKey",required(c.sortKey(),"sortKey"));n.put("uniqueId",required(c.uniqueId(),"uniqueId"));if(c.asOf()!=null)n.put("asOf",c.asOf().toString());n.put("expiresAt",clock.instant().plus(ttl).toString());return tokenForTesting(n.toString());}
 public Cursor decode(String token,String resource,String filterHash,String sort){try{if(token==null||token.isBlank())throw reject(RejectionReason.MALFORMED);String[] p=token.split("\\.",-1);if(p.length!=2||p[0].isBlank()||p[1].isBlank())throw reject(RejectionReason.MALFORMED);byte[] payload=decode(p[0]);if(!MessageDigest.isEqual(signUnchecked(payload),decode(p[1])))throw reject(RejectionReason.TAMPERED);JsonNode n=mapper.readTree(payload);if(!n.isObject())throw reject(RejectionReason.MALFORMED);if(!n.has("v")||n.path("v").asInt(-1)!=VERSION)throw reject(RejectionReason.UNSUPPORTED_VERSION);String r=text(n,"resource"),f=text(n,"filterHash"),s=text(n,"sort"),k=text(n,"sortKey"),id=text(n,"uniqueId");Instant exp=Instant.parse(text(n,"expiresAt"));Instant as=n.has("asOf")?Instant.parse(text(n,"asOf")):null;if(!clock.instant().isBefore(exp))throw reject(RejectionReason.EXPIRED);if(!Objects.equals(resource,r))throw reject(RejectionReason.RESOURCE_MISMATCH);if(!Objects.equals(filterHash,f))throw reject(RejectionReason.FILTER_MISMATCH);if(!Objects.equals(sort,s))throw reject(RejectionReason.SORT_MISMATCH);return new Cursor(r,f,s,k,id,as,exp);}catch(InvalidCursorException e){throw e;}catch(Exception e){throw reject(RejectionReason.MALFORMED);}}
 public String tokenForTesting(String json){byte[] p=json.getBytes(StandardCharsets.UTF_8);return Base64.getUrlEncoder().withoutPadding().encodeToString(p)+"."+Base64.getUrlEncoder().withoutPadding().encodeToString(signUnchecked(p));}private byte[] signUnchecked(byte[] p){try{return sign(p);}catch(Exception e){throw new IllegalStateException(e);}}private byte[] sign(byte[] p)throws Exception{Mac m=Mac.getInstance(ALGORITHM);m.init(new SecretKeySpec(secret,ALGORITHM));return m.doFinal(p);}private static byte[] decode(String v){return Base64.getUrlDecoder().decode(v);}private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v;}private static String text(JsonNode n,String f){JsonNode v=n.get(f);if(v==null||!v.isTextual()||v.asText().isBlank())throw reject(RejectionReason.MISSING_FIELD);return v.asText();}private static InvalidCursorException reject(RejectionReason r){return new InvalidCursorException(r);}
 public record Cursor(String resource,String filterHash,String sort,String sortKey,String uniqueId,Instant asOf,Instant expiresAt){public Cursor withExpiresAt(Instant v){return new Cursor(resource,filterHash,sort,sortKey,uniqueId,asOf,v);}}public enum RejectionReason{MALFORMED,TAMPERED,EXPIRED,RESOURCE_MISMATCH,FILTER_MISMATCH,SORT_MISMATCH,MISSING_FIELD,UNSUPPORTED_VERSION}public static final class InvalidCursorException extends IllegalArgumentException{private final RejectionReason reason;public InvalidCursorException(RejectionReason r){super(r.name().toLowerCase());reason=r;}public RejectionReason reason(){return reason;}}
}
