apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vnshop-staging
resources:
- ../../base
- namespace.yaml
- ingress.yaml
- keycloak-reconcile-job.yaml
replicas:
- name: vnshop-frontend
  count: 2
- name: vnshop-api-gateway
  count: 2
- name: vnshop-cart
  count: 2
- name: vnshop-configuration
  count: 2
- name: vnshop-inventory
  count: 2
- name: vnshop-invoice
  count: 2
- name: vnshop-messaging
  count: 2
- name: vnshop-monitoring
  count: 2
- name: vnshop-notification
  count: 2
- name: vnshop-order
  count: 2
- name: vnshop-payment
  count: 2
- name: vnshop-product
  count: 2
- name: vnshop-recommendations
  count: 2
- name: vnshop-search
  count: 2
- name: vnshop-seller-finance
  count: 2
- name: vnshop-shipping
  count: 2
- name: vnshop-user
  count: 2
- name: vnshop-video-moderator
  count: 2
- name: vnshop-video-transcoder
  count: 2
images:
- name: ghcr.io/dang232/vnshop-frontend
  newName: ghcr.io/dang232/vnshop-frontend
  digest: sha256:84c39dcd73b1b5c3ec15e46b968f609889cf4e395d610482e3d0e7d5a8f6f84c
- name: ghcr.io/dang232/vnshop-api-gateway
  newName: ghcr.io/dang232/vnshop-api-gateway
  digest: sha256:005b707e032fb2ab221c1a0aabae537af99113cd9bdcd2e697b026feab397891
- name: ghcr.io/dang232/vnshop-cart
  newName: ghcr.io/dang232/vnshop-cart
  digest: sha256:6e64076cfca8128c3a309e4eacfe02890a1adc7696480ce4c8bff213c12df21f
- name: ghcr.io/dang232/vnshop-configuration
  newName: ghcr.io/dang232/vnshop-configuration
  digest: sha256:e7b67073438675af218109d893c5526400678317a80484b2f8b912376ade9692
- name: ghcr.io/dang232/vnshop-inventory
  newName: ghcr.io/dang232/vnshop-inventory
  digest: sha256:2c8319b775213c778c25ecbb0c2ea9ed55ea75a3860ce5e02166e49f946352ba
- name: ghcr.io/dang232/vnshop-invoice
  newName: ghcr.io/dang232/vnshop-invoice
  digest: sha256:f7e0abe57f631aaf434a669ca41980dfce2c625fa3d397e05be03bd2d7491013
- name: ghcr.io/dang232/vnshop-messaging
  newName: ghcr.io/dang232/vnshop-messaging
  digest: sha256:44d74486041cbaa3928de1a8b3835b58d7f3ba7f0097e94a2ae1999cb71621eb
- name: ghcr.io/dang232/vnshop-monitoring
  newName: ghcr.io/dang232/vnshop-monitoring
  digest: sha256:f1ee32b6f5fa72c2f4865f9c3f4bd2e1390fe0d57af98d3dc242a82039aa37af
- name: ghcr.io/dang232/vnshop-notification
  newName: ghcr.io/dang232/vnshop-notification
  digest: sha256:8a4843fcb29671df3106312111f2c0205362e9ec8f27fde2db3ce09aa1fa576a
- name: ghcr.io/dang232/vnshop-order
  newName: ghcr.io/dang232/vnshop-order
  digest: sha256:7acc035ccc661e777c3c2d6e8e5d1b8ee2a5c1e6e8749d619e09320c9ef75a63
- name: ghcr.io/dang232/vnshop-payment
  newName: ghcr.io/dang232/vnshop-payment
  digest: sha256:8f87a433eb71927211a2994cab17da956ec82b977f746580bed72fc746660d40
- name: ghcr.io/dang232/vnshop-product
  newName: ghcr.io/dang232/vnshop-product
  digest: sha256:59993e77053e655401dc9285228d252cb59aefbc59cd7bd6ecd9d578a299d586
- name: ghcr.io/dang232/vnshop-recommendations
  newName: ghcr.io/dang232/vnshop-recommendations
  digest: sha256:53247cd3fc72c071493c53f24cdf67bd244e8ca62ddf3f021e51da61f32405a2
- name: ghcr.io/dang232/vnshop-search
  newName: ghcr.io/dang232/vnshop-search
  digest: sha256:2e9e975a15837397ced4a72ceb31d19fe0589d91b7a34d9add7fe548f20b816b
- name: ghcr.io/dang232/vnshop-seller-finance
  newName: ghcr.io/dang232/vnshop-seller-finance
  digest: sha256:9defa5cbff8e25a2954ae6b244d658d8fe95083930ed97458e9a2a596523a982
- name: ghcr.io/dang232/vnshop-shipping
  newName: ghcr.io/dang232/vnshop-shipping
  digest: sha256:9cb7d22ae8fd6c6db91f4d84731463f46bb5e3b5579f8348519fa06e7cb976eb
- name: ghcr.io/dang232/vnshop-user
  newName: ghcr.io/dang232/vnshop-user
  digest: sha256:b84532d8e091f6c8f5eb52773e25cf247c00ea77457a78f4e78a4d6d21fdca7d
- name: ghcr.io/dang232/vnshop-video-moderator
  newName: ghcr.io/dang232/vnshop-video-moderator
  digest: sha256:99d03ec759a260f97eb48a065ae34e854b902f5f0010f73c17079f06be9d7e1d
- name: ghcr.io/dang232/vnshop-video-transcoder
  newName: ghcr.io/dang232/vnshop-video-transcoder
  digest: sha256:4c3e1375381c09b958b71ec9bab123320468bd83011656b196b2789d0f13d65e
configMapGenerator:
- name: vnshop-keycloak-realm
  files:
  - vnshop-realm.json
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "-20"
generatorOptions:
  disableNameSuffixHash: true

patches:
- path: configmap-env.yaml
- path: keycloak-import-patch.yaml
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-frontend
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-api-gateway
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-cart
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-configuration
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-inventory
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-invoice
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-messaging
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-monitoring
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-notification
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-order
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-payment
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-product
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-recommendations
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-search
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-seller-finance
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-shipping
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-user
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-video-moderator
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-video-transcoder
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
