apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- sealedsecret.yaml
- network-policies.yaml
- platform-services.yaml
- workloads.yaml
- migration-job.yaml
- kafka-bootstrap-job.yaml
- storage-bootstrap-job.yaml
- backup-jobs.yaml
- monitoring.yaml
