package com.vnshop.productservice.infrastructure.web.pagination;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;

class AdminCursorCodecTest {
    private static final Instant NOW = Instant.parse("2026-08-08T00:00:00Z");
    private static final Clock CLOCK = Clock.fixed(NOW, ZoneOffset.UTC);
    private static final AdminCursorCodec.Cursor CURSOR = new AdminCursorCodec.Cursor("reviews", "filter-hash", "createdAt:desc,id:desc", "2026-08-07T23:59:00Z", "review-42", NOW, null);
    private AdminCursorCodec codec() { return new AdminCursorCodec("test-secret", Duration.ofMinutes(5), CLOCK); }
    @Test void omittedAsOf_roundTripsAsNull() { String token = signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"); assertThat(codec().decode(token, "reviews", "filter-hash", "createdAt:desc,id:desc").asOf()).isNull(); }
    @Test void unsupportedVersions_areRejected() { assertReason(signed("{\"v\":0,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.UNSUPPORTED_VERSION); assertReason(signed("{\"v\":2,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.UNSUPPORTED_VERSION); }
    @Test void requiredFields_wrongOrBlank_areRejected() { assertReason(signed("{\"v\":1,\"resource\":\"\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MISSING_FIELD); assertReason(signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":1,\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MISSING_FIELD); assertReason(signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":null,\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MISSING_FIELD); assertReason(signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MISSING_FIELD); assertReason(signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"k\",\"uniqueId\":\"review-42\",\"expiresAt\":1}"), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MISSING_FIELD); }
    @Test void oversizedToken_isRejected() { assertReason("x".repeat(4097), "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MALFORMED); }
    @Test void encode_rejectsOversizedToken() { AdminCursorCodec.Cursor oversized = new AdminCursorCodec.Cursor("reviews", "filter-hash", "createdAt:desc,id:desc", "k", "x".repeat(5000), NOW, null); assertThatThrownBy(() -> codec().encode(oversized)).isInstanceOf(AdminCursorCodec.CursorEncodingException.class); }
    @Test void roundTrip_preservesScopedPayload() { String token = codec().encode(CURSOR); assertThat(codec().decode(token, "reviews", "filter-hash", "createdAt:desc,id:desc")).isEqualTo(CURSOR.withExpiresAt(NOW.plusSeconds(300))); assertThat(token).doesNotContain("reviews").matches("[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"); }
    @Test void tampering_isRejectedWithTypedReason() { String token = codec().encode(CURSOR); String tampered = token.substring(0, token.length() - 1) + (token.endsWith("A") ? "B" : "A"); assertThatThrownBy(() -> codec().decode(tampered, "reviews", "filter-hash", "createdAt:desc,id:desc")).isInstanceOf(AdminCursorCodec.InvalidCursorException.class).extracting(e -> ((AdminCursorCodec.InvalidCursorException) e).reason()).isEqualTo(AdminCursorCodec.RejectionReason.TAMPERED); }
    @Test void expiry_isRejected() { String token = signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"sortKey\":\"2026-08-07T23:59:00Z\",\"uniqueId\":\"review-42\",\"expiresAt\":\"2026-08-07T23:59:00Z\"}"); assertThatThrownBy(() -> codec().decode(token, "reviews", "filter-hash", "createdAt:desc,id:desc")).isInstanceOf(AdminCursorCodec.InvalidCursorException.class).extracting(e -> ((AdminCursorCodec.InvalidCursorException) e).reason()).isEqualTo(AdminCursorCodec.RejectionReason.EXPIRED); }
    @Test void scopeMismatches_areTyped() { String token = codec().encode(CURSOR); assertReason(token, "videos", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.RESOURCE_MISMATCH); assertReason(token, "reviews", "other-filter", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.FILTER_MISMATCH); assertReason(token, "reviews", "filter-hash", "name:asc,id:asc", AdminCursorCodec.RejectionReason.SORT_MISMATCH); }
    @Test void malformedPayload_isRejected() { assertReason("not-a-token", "reviews", "filter-hash", "createdAt:desc,id:desc", AdminCursorCodec.RejectionReason.MALFORMED); }
    @Test void missingRequiredField_isRejected() { String token = signed("{\"v\":1,\"resource\":\"reviews\",\"filterHash\":\"filter-hash\",\"sort\":\"createdAt:desc,id:desc\",\"expiresAt\":\"2026-08-08T00:05:00Z\"}"); assertThatThrownBy(() -> codec().decode(token, "reviews", "filter-hash", "createdAt:desc,id:desc")).isInstanceOf(AdminCursorCodec.InvalidCursorException.class).extracting(e -> ((AdminCursorCodec.InvalidCursorException) e).reason()).isEqualTo(AdminCursorCodec.RejectionReason.MISSING_FIELD); }
    private void assertReason(String token, String resource, String filterHash, String sort, AdminCursorCodec.RejectionReason reason) { assertThatThrownBy(() -> codec().decode(token, resource, filterHash, sort)).isInstanceOf(AdminCursorCodec.InvalidCursorException.class).extracting(e -> ((AdminCursorCodec.InvalidCursorException) e).reason()).isEqualTo(reason); }
    private static String signed(String json) { try { byte[] payload = json.getBytes(java.nio.charset.StandardCharsets.UTF_8); javax.crypto.Mac mac = javax.crypto.Mac.getInstance("HmacSHA256"); mac.init(new javax.crypto.spec.SecretKeySpec("test-secret".getBytes(java.nio.charset.StandardCharsets.UTF_8), "HmacSHA256")); return java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(payload) + "." + java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(mac.doFinal(payload)); } catch (Exception exception) { throw new IllegalStateException(exception); } }
}
