apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vnshop-prod
resources:
- ../../base
- namespace.yaml
- ingress.yaml
- keycloak-reconcile-job.yaml
replicas:
- name: vnshop-frontend
  count: 3
- name: vnshop-api-gateway
  count: 3
- name: vnshop-cart
  count: 3
- name: vnshop-configuration
  count: 3
- name: vnshop-inventory
  count: 3
- name: vnshop-invoice
  count: 3
- name: vnshop-messaging
  count: 3
- name: vnshop-monitoring
  count: 3
- name: vnshop-notification
  count: 3
- name: vnshop-order
  count: 3
- name: vnshop-payment
  count: 3
- name: vnshop-product
  count: 3
- name: vnshop-recommendations
  count: 3
- name: vnshop-search
  count: 3
- name: vnshop-seller-finance
  count: 3
- name: vnshop-shipping
  count: 3
- name: vnshop-user
  count: 3
- name: vnshop-video-moderator
  count: 3
- name: vnshop-video-transcoder
  count: 3
images:
- name: ghcr.io/dang232/vnshop-frontend
  newName: ghcr.io/dang232/vnshop-frontend
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-api-gateway
  newName: ghcr.io/dang232/vnshop-api-gateway
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-cart
  newName: ghcr.io/dang232/vnshop-cart
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-configuration
  newName: ghcr.io/dang232/vnshop-configuration
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-inventory
  newName: ghcr.io/dang232/vnshop-inventory
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-invoice
  newName: ghcr.io/dang232/vnshop-invoice
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-messaging
  newName: ghcr.io/dang232/vnshop-messaging
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-monitoring
  newName: ghcr.io/dang232/vnshop-monitoring
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-notification
  newName: ghcr.io/dang232/vnshop-notification
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-order
  newName: ghcr.io/dang232/vnshop-order
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-payment
  newName: ghcr.io/dang232/vnshop-payment
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-product
  newName: ghcr.io/dang232/vnshop-product
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-recommendations
  newName: ghcr.io/dang232/vnshop-recommendations
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-search
  newName: ghcr.io/dang232/vnshop-search
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-seller-finance
  newName: ghcr.io/dang232/vnshop-seller-finance
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-shipping
  newName: ghcr.io/dang232/vnshop-shipping
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-user
  newName: ghcr.io/dang232/vnshop-user
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-video-moderator
  newName: ghcr.io/dang232/vnshop-video-moderator
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
- name: ghcr.io/dang232/vnshop-video-transcoder
  newName: ghcr.io/dang232/vnshop-video-transcoder
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
configMapGenerator:
- name: vnshop-keycloak-realm
  files:
  - vnshop-realm-prod.json
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "-20"
generatorOptions:
  disableNameSuffixHash: true

patches:
- path: configmap-env.yaml
- path: keycloak-import-patch.yaml
- target:
    kind: PeerAuthentication
    name: default
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        vnshop.io/transport-security: strict-mtls
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-frontend
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-api-gateway
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-cart
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-configuration
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-inventory
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-invoice
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-messaging
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-monitoring
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-notification
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-order
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-payment
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-product
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-recommendations
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-search
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-seller-finance
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-shipping
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-user
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-video-moderator
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
- target:
    kind: HorizontalPodAutoscaler
    name: vnshop-video-transcoder
  patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 10
