package com.vnshop.sellerfinanceservice.domain;

public enum LedgerJournalType {
    SELLER_CREDIT,
    SETTLEMENT_RELEASE,
    REFUND_REVERSAL,
    CHARGEBACK_HOLD,
    CHARGEBACK_RELEASE,
    CHARGEBACK_FINALIZE,
    PAYOUT_RESERVATION,
    PAYOUT_REVERSAL,
    PAYOUT_COMPLETION,
    PAYOUT_FAILURE,
    MIGRATION_OPENING_BALANCE
}
